version: 2
registries:
  azure-artifacts: 
    type: nuget-feed
    url: "https://pkgs.dev.azure.com/FutureIRAS/Research%20Systems%20Programme/_packaging/rsp-nuget-feed/nuget/v3/index.json"
    username: "Dependabot"
    password: ${{secrets.AZURE_DEVOPS_PAT}} # This expires on 22/05/2026
updates:
  # Application project
  - package-ecosystem: "nuget"
    directory: "/"
    registries: 
      - azure-artifacts
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[Dependabot]"
      include: "scope"
    labels:
      - "dependencies"
      - "application"
    open-pull-requests-limit: 3
    target-branch: "main"