name: $(Build.DefinitionName)_$(Build.SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

pool:
  vmImage: "Ubuntu-latest"

trigger:
  - main

parameters:
  - name: env
    displayName: Environment
    type: string
    default: dev
    values:
      - dev
      - systemtest_manual
      - systemtest_auto
      - system_integration_test
      - uat
      - pre_prod
      - production
  - name: devops_library_branch
    displayName: DevOps Library Branch
    type: string
    default: main
  - name: servicedefaults_library_branch
    displayName: Service Defaults Library Branch
    type: string
    default: main
  - name: run_github_security_scan
    displayName: Run GitHub Advanced Security Scan
    type: boolean
    default: false
  - name: run_sonarcloud_analysis
    displayName: Run Sonar Cloud Analysis
    type: boolean
    default: true
  - name: skip_deployment
    displayName: Skip Deployment
    type: boolean
    default: true
  - name: browser
    displayName: Select a Browser
    type: string
    default: chromium
    values:
      - chromium
      - safari
      - firefox
  - name: tests_run_timeout
    type: number
    displayName: Automated Tests Run Timeout
    default: 10

variables:
  - group: 'UserServiceContainerApp'
  - group: 'Test Automation'
  - name: vstsFeed
    value: "0e030eb0-cb72-4f42-b99a-26e6544271c3/0a3e0ad2-23b6-4e8b-ae12-cd6d01fe97e7"
  - name: solution
    value: "**/*.sln"
  - name: project
    value: "**/*.csproj"
  - name: projectForContainerBuild
    value: "Rsp.UsersService.csproj"
  - name: buildConfiguration
    value: "Release"
  - name: service_connection
    ${{ if in(parameters.env, 'dev') }}:
      value: "ARM Dev Connection New"
    ${{ if in(parameters.env, 'systemtest_auto') }}:
      value: "ARM Automated Test Connection"  
    ${{ if in(parameters.env, 'systemtest_manual') }}:
      value: "ARM Manual Test Connection"

resources:
  repositories:
    - repository: library
      type: github
      name: 'HealthResearchAuthority/rsp-azure-devops-library'
      endpoint: AzureDevOpsToGitHubConnection
      ref: ${{ parameters.devops_library_branch }}
    - repository: e2e_tests
      type: github
      name: 'HealthResearchAuthority/rsp-iras-qa'
      endpoint: AzureDevOpsToGitHubConnection
      ref: main
    - repository: api_tests
      type: github
      name: 'HealthResearchAuthority/rsp-iras-api-tests'
      endpoint: AzureDevOpsToGitHubConnection
      ref: main
    - repository: service_defaults
      type: github
      name: 'HealthResearchAuthority/rsp-service-defaults'
      endpoint: AzureDevOpsToGitHubConnection
      ref: ${{ parameters.servicedefaults_library_branch }}

stages:
  - stage: dev
    variables: 
    - group: 'DevelopmentEnvironment'
    condition: eq('${{ parameters.env }}', 'dev')
    jobs:
      - template: jobs/build.yaml@library
        parameters:
          run_github_security_scan: ${{ parameters.run_github_security_scan }}
          sonar_project_key: HealthResearchAuthority_rsp-usermanagement-service
          sonar_project_name: rsp-usermanagement-service
          run_sonarcloud_analysis: ${{ parameters.run_sonarcloud_analysis }}
          install_aspire: true
          service_defaults_repo: service_defaults
          
      - ${{ if eq(parameters.skip_deployment, false) }}:
        - template: jobs/deploy.yaml@library
          parameters:
            install_aspire: true
            service_defaults_repo: service_defaults

  - stage: systemtest_auto
    variables: 
    - group: 'STAutoEnvironment'
    condition: eq('${{ parameters.env }}', 'systemtest_auto')
    jobs:
      - job:
        steps:
        - script: |
            echo 'env: system test auto'
      - template: jobs/deploy.yaml@library
        parameters:
          install_aspire: true
          service_defaults_repo: service_defaults
      - ${{ if eq(variables.run_e2e_tests, 'true') }}:
        - template: jobs/e2e_tests.yaml@library
          parameters:
            browser: ${{ parameters.browser }}
            repo: e2e_tests
            tests_run_timeout: ${{ parameters.tests_run_timeout }}

      - ${{ if eq(variables.run_api_tests, 'true') }}:
        - template: jobs/api_tests.yaml@library
          parameters:
            repo: api_tests

  - stage: systemtest_manual
    variables: 
    - group: 'STManualEnvironment'
    condition: eq('${{ parameters.env }}', 'systemtest_manual') 
    jobs:
      - template: jobs/deploy.yaml@library
        parameters:
          install_aspire: true
          service_defaults_repo: service_defaults

  - stage: system_integration_test
    dependsOn: systemtest_manual
    jobs:
    - job:
      steps:
      - script: |
          echo 'env: system integration test'

  - stage: uat
    dependsOn: system_integration_test
    jobs:
    - job:
      steps:
      - script: |
          echo 'env: uat'

  - stage: pre_prod
    dependsOn: uat
    jobs:
    - job:
      steps:
      - script: |
          echo 'env: pre prod'

  - stage: production
    dependsOn: pre_prod
    jobs:
    - job:
      steps:
      - script: |
          echo 'env: production'
